spring:
  application:
    name: project_getJobs_Spring
  datasource:
    url: jdbc:postgresql://localhost:5433/jobsdb
    username: postgres
    password: 18051974
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

gemini:
  gemini.api-key: ${GEMINI_API_KEY}